### PR TITLE
add optional email capturing

### PR DESCRIPTION
**Pull request by s9gf4ult**
Add parameter `include_email` to `AccountVerifyCredentials` query

### CODE REVIEW

**Comment by s9gf4ult** [comment]
According to https://dev.twitter.com/rest/reference/get/account/verify_credentials

**Comment by s9gf4ult** [comment]
@himura merge ?

**Comment by dredozubov** [comment]
Can we please merge this? I'd like to see this patch in upstream too.

**Comment by s9gf4ult** [comment]
@himura stop ignore this thread!

**Pull request merged**
