### PR TITLE
first commit for Twitter API update

### PR DESCRIPTION
**Pull request by cdupont**
I made some simple changes to make `directMessagesNew` work:
https://github.com/himura/twitter-conduit/issues/61

It's not complete but I wanted some help from you, probably corrections on the style.
Probably deeper changes are needed. For instance using Network.HTTP.Simple instead of  Network.HTTP.Conduit would make use of JSON easier: https://github.com/snoyberg/http-client/blob/master/http-conduit/Network/HTTP/Conduit.hs#L7
Also creating new datatypes to represent events would be better.
Cheers!

### CODE REVIEW

**Comment by cdupont** [comment]
Any news on that? @himura

**Comment by himura** [comment]
Sorry for my late replay.

I've started to fix deprecated DM APIs in #65, but there is still a lot of things to fix (e.g. Add support DELETE method to APIRequest).

**Comment by cdupont** [comment]
That is great, thanks!

**Comment by himura** [comment]
:bowing_man:

**Pull request closed without merging**
